### ISSUE TITLE
forgot the last bullet

### ISSUE THREAD

**Issue by Nahui** [Nahui/hyf-javascript1#2]
Forgot the last bullet in the readme file

**Comment by Nahui** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Valeria](https://trello.com/c/WwfNnBjM/85-valeria)

**Comment by Usaghir** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Raja Umer](https://trello.com/c/hLsqZ2oV/119-raja-umer)

**Comment by SweetSue** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Kiki](https://trello.com/c/ZgujMD1d/123-kiki)
